server {
    listen 80;

    # =========================
    # HEALTH (MUST BE FIRST)
    # =========================
    location = /health {
        return 200 "OK";
        add_header Content-Type text/plain;
    }

    # =========================
    # API
    # =========================
    location /api/ {
        proxy_pass http://backend-service/;
    }

    # =========================
    # FRONTEND (Angular SPA)
    # =========================
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}