apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      serviceAccountName: jenkins
      containers:
        - name: jenkins
          image: jenkins/jenkins:lts
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
            - containerPort: 50000
          
          # 👇 THIS IS WHERE volumeMounts GO (INSIDE container)
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home

      # 👇 THIS IS WHERE volumes GO (INSIDE pod spec, NOT container)
      volumes:
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: jenkins-pvc
          